on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python update_readme.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update list in README
